In [12]:
!pip3 install bokeh==2.4.3
!pip3 install colorcet==3.0.0
!pip3 install fluidsynth==0.2
!pip3 install librosa==0.9.2
!pip3 install numpy==1.23.3
!pip3 install pandas==1.5.0
!pip3 install PyYAML==6.0
!pip3 install scikit_learn==1.1.3
!pip3 install scipy==1.9.1
!pip3 install soundfile==0.11.0
!pip3 install tqdm==4.64.1
#to install other packages ! before the command
#To do:
#Install the rest of the packages for the library. 
#Import the github repository
#Start implementing the functions for the new parameters
#Clean and write the State of the Art

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 18.5 MB 4.8 MB/s eta 0:00:01
     |████████████████████████████████| 3.0 MB 3.4 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 1.6 MB 2.4 MB/s eta 0:00:01
     |████████████████████████████████| 87 kB 9.8 MB/s  eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Defaulting to user installation because normal site-packages is not writeable
  Created wheel for fluidsynth: filename=fluidsynth-0.2-py3-none-any.whl size=4514 sha256=e738be212fcbf6e2512bcdcf26a98ef69b430b28f5e8cc5f699fd5da0076a471
  Stored in directory: /Users/didacfreirecastane/Library/Caches/pip/wheels/26/

In [2]:
import numpy as np

In [9]:
a = np.array([1,2,3,2,3])
print(a)

[1 2 3 2 3]


In [46]:
def gen_complex_sine(k, N):
    """Generate one of the complex sinusoids used in the DFT from its frequency index and the DFT length.
    
    Args:
        k (integer): frequency index of the complex sinusoid of the DFT
        N (integer) = length of complex sinusoid, DFT length, in samples
        
    Returns:
        np.array: array with generated complex sinusoid (length N)
        
    """
    ### your code here
    n = np.arange(N)

    return np.exp((-1) * 1j * 2 * np.pi * k * n / N)
def dft(x):
    """Compute the DFT of a signal.
    
    Args:
        x (numpy array): input sequence of length N
        
    Returns:
        np.array: N point DFT of the input sequence x
    """
    ## Your code here
    X = np.array([])
    n = np.arange(x.size)
    for k in range(x.size):
      complSine = gen_complex_sine(k,x.size)
      X = np.append(X,sum(x*(complSine)))
    return X
def gen_mag_spec(x):
    """Compute magnitude spectrum of a signal.
    
    Args:
        x (np.array): input sequence of length N
        
    Returns:
        np.array: magnitude spectrum of the input sequence x (length N)
        
    """
    ### your code here
    X = np.array([])
    n = np.arange(x.size)
    for k in range(x.size):
      complSine = gen_complex_sine(k,x.size)
      X = np.append(X, sum(x * complSine))
    return np.abs(X)

def balance(DFT:np.array):
    balance = []
    for i in DFT:
       balance.append( 1 - (i)/DFT.size ) 
    return balance


In [48]:

#testing balance
#generate signal
x = np.cos(2*np.pi*200.0*np.arange(512)/1000)
#getting dft
signal_dft = dft(x)
#magnitude spectrum
mag_spectrum = gen_mag_spec(signal_dft)
#balance
signal_balance = balance(mag_spectrum)
print(signal_balance)
print(sum(signal_balance)/len(signal_balance))


[-8.282263763703668e-14, 0.6909830056249624, 1.1546319456101628e-14, 0.6909830056250712, 0.1909830056250923, 0.19098300562506587, 0.690983005624958, 1.709743457922741e-14, 0.6909830056250329, 0.19098300562502957, 0.19098300562506842, 0.6909830056249922, 3.6637359812630166e-14, 0.6909830056250498, 0.19098300562507042, 0.19098300562505677, 0.6909830056250057, 5.340172748447003e-14, 0.6909830056251298, 0.19098300562505865, 0.1909830056251125, 0.6909830056250424, 1.7985612998927536e-14, 0.690983005625139, 0.19098300562502335, 0.19098300562506687, 0.6909830056250494, 2.4868995751603507e-14, 0.6909830056250919, 0.19098300562501636, 0.1909830056249714, 0.6909830056250496, 4.7406523151494184e-14, 0.6909830056251024, 0.19098300562503834, 0.19098300562515425, 0.6909830056251325, -1.5987211554602254e-14, 0.6909830056250181, 0.19098300562509785, 0.19098300562519532, 0.6909830056250625, 4.463096558993129e-14, 0.6909830056250565, 0.19098300562501813, 0.19098300562514636, 0.6909830056250255, 7.516209

In [45]:
#to do evennes and entropy
def evenness(DFT:np.array):
    evenness = []
    for coefficient in DFT:
        evenness.append(coefficient/DFT.size)
    return evenness

evenness_array = evenness(mag_spectrum)
#mean evenness?
print(sum(evenness_array)/len(evenness_array))

0.6472420912096845


In [42]:

rhythm = np.array([1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0])

def get_probability_mass_function(rhythm):
    #get the distance between the 1's in rhythm
    onsets = np.array([])

    onset_positions = np.where(rhythm == 1)[0]
    print(onset_positions)
    mass_function = np.zeros(rhythm.size)
    for i in range(onset_positions.size):
        print(i)
        if i != onset_positions.size - 1:
            onset_size = onset_positions[i+1] - onset_positions[i]
        else:
            onset_size = rhythm.size - onset_positions[i]  
        mass_function[onset_size] += 1
        onsets = np.append(onsets,onset_size)

    print(onsets,mass_function)
    return onsets,mass_function
    
onsets,mass_function = get_probability_mass_function(rhythm)



def interonset_entropy(probability_mass_function,onsets):
    '''
    probability_mass_function: array that denotes how many onsets of each duration we have all divided by the total of onsets
    onsets: array of onsets, will get the K which is the number on the function
    '''
    k = onsets.size
    entropy = 0
    for i in range(probability_mass_function.size):
        if probability_mass_function[i] == 0:
            continue
        entropy += -(probability_mass_function[i]/k )*(np.log2(probability_mass_function[i]/k))

    return entropy

entropy = interonset_entropy(mass_function,onsets)


[ 0  3  6 10 12]
0
1
2
3
4
[3. 3. 4. 2. 4.] [0. 0. 1. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1.5219280948873621
